apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mymetallb
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.31.217.210-172.31.217.220
