apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv01
  nfs:
    server: 172.31.2.52
    path: /mnt/k8s
